name: Terraform Deploy

on:
  push:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.4.0

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2

      - name: Terraform Init
        run: terraform init -reconfigure

      - name: Remove Stuck IAM Resources
        run: |
          terraform state rm aws_iam_role.eks_admin_role || true
          terraform state rm aws_iam_role_policy_attachment.eks_admin_AmazonEKSClusterPolicy || true
          terraform state rm aws_iam_role_policy_attachment.eks_admin_AmazonEKSServicePolicy || true
          terraform state rm aws_iam_role_policy_attachment.eks_admin_AmazonVPCFullAccess || true

      - name: Terraform Destroy
        run: terraform destroy --auto-approve        
        



